In [3]:
import numpy as np

In [21]:
def sqrt(S):
    eps = 1
    prev = 2 * 10**(np.floor(np.log10(S))/2)
    while eps > 0.00001:
        guess = (prev + S/prev)/2
        eps = abs(prev-guess)
        prev = guess
    return guess    

In [28]:
%%timeit
sqrt(999)

The slowest run took 9.14 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 7.9 µs per loop


In [96]:
x= np.array([[0,2,3], [4,5,5], [7,8,10]])
prev = x.mean(axis=0)

In [91]:

eps=1

while eps > 0.00001:
    dists = np.linalg.norm(x - prev, axis=1)
    num=np.sum(x/dists,axis=0)
    denom=np.sum(1/dists)
    guess = num/denom
    eps=np.linalg.norm(guess - prev)
    prev = guess



KeyboardInterrupt: 

In [97]:
dists = np.linalg.norm(x - prev, axis=1)

In [101]:
dists

array([ 5.60753461,  1.05409255,  6.00925213])

In [99]:
x

array([[ 0,  2,  3],
       [ 4,  5,  5],
       [ 7,  8, 10]])

In [100]:
prev

array([ 3.66666667,  5.        ,  6.        ])